### PR TITLE
Unset CONFIG_DM_VERITY

### PR DESCRIPTION
**Pull request by Keij0**
Takes care of annoying 5 second bootup delay as seen on previous builds

### CODE REVIEW

**Comment by Keij0** [comment]
You might test if it works with P9 Lite's obscure abomination of U-Boot, I don't have the defice as the device I rooted belonged to my friend.

**Comment by Meticulus** [comment]
I'll try it next set of builds...

**Comment by dady8889** [comment]
@Meticulus I think you can close this, cause the flag does nothing.

**Comment by Meticulus** [comment]
Really, I never got around to testing or even looking at it but I thought it might do something....

**Comment by reza16927** [comment]
Tanks

**Pull request closed without merging**
